{% set name = "protected-classification" %}
{% set version = "0.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/protected-classification-{{ version }}.tar.gz
  sha256: 2e37927fe1199db43817019ae0cc3a4c719a59a6d5406ebb09589ad4c888ce65

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - python >=3.6
    - scikit-learn

test:
  imports:
    - protected_classification
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ip200/protected-classification
  summary: Protected Classification package
  license: MIT
  license_file: LICENSE.TXT

extra:
  recipe-maintainers:
    - ip200
