{% set name = "protected-classification" %}
{% set version = "0.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/protected-classification-{{ version }}.tar.gz
  sha256: 5e0465bba3d8755314c558d8180ad3986e945b24dd6a9239800cbfbd2c41f17e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - python >=3.6
    - scikit-learn

test:
  imports:
    - protected_classification
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ip200/protected-classification
  summary: Protected Classification package
  license: MIT
  license_file: LICENSE.TXT

extra:
  recipe-maintainers:
    - ip200
